name: CI (Unit)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libpq-dev

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r tests/requirements.txt
          pip install ruff mypy bandit

      - name: Lint (ruff)
        run: ruff check agents mcp_bus common tests

      - name: Type check (mypy)
        run: mypy --ignore-missing-imports --install-types --non-interactive . || true

      - name: Security scan (bandit)
        run: bandit -q -r agents mcp_bus common || true

      - name: Run unit tests (subset)
        run: pytest -q tests/test_common_schemas.py tests/test_mcp_bus_idempotency.py tests/test_security_and_limits.py
