name: CI (Unit)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Debug repo contents
        run: |
          pwd
          ls -la

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libpq-dev

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "requirements.txt not found, skipping"; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; else echo "requirements-dev.txt not found, skipping"; fi
          # Fallback installs if requirements-dev.txt not present
          pip install ruff mypy bandit pytest || true
          # Minimal runtime deps for unit tests (noop if already from requirements-dev.txt)
          pip install "pydantic>=2" requests fastapi uvicorn httpx || true

      - name: Lint (ruff)
        run: ruff check mcp_bus common tests

      - name: Type check (mypy)
        run: mypy --ignore-missing-imports --install-types --non-interactive . || true

      - name: Security scan (bandit)
        run: bandit -q -r mcp_bus common || true

      - name: Run unit tests (subset)
        run: |
          targets=()
          for f in tests/test_common_schemas.py tests/test_mcp_bus_idempotency.py tests/test_security_and_limits.py; do
            if [ -f "$f" ]; then targets+=("$f"); fi
          done
          if [ ${#targets[@]} -gt 0 ]; then
            echo "Running targeted tests: ${targets[*]}"
            pytest -q "${targets[@]}"
          else
            echo "Targeted tests not found; running full test suite"
            pytest -q
          fi
