name: CI (Dockerless)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libpq-dev
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # Minimal install for unit tests; avoid heavy optional deps
          pip install -r requirements.txt
          pip install pytest pytest-cov ruff
      - name: Lint (ruff)
        run: ruff check .
      - name: Run unit tests (no integration)
        env:
          PYTHONPATH: .
        run: |
          pytest -q
