name: CI - Pytest (conda)

# Manual dispatch workflow for running unit tests in a reproducible conda env
on:
  workflow_dispatch: {}

jobs:
  test:
    name: Run tests (conda environment)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Miniconda and create environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.11
          auto-update-conda: true
          activate-environment: justnews-pinned
          environment-file: environment.yml
          use-mamba: true

      - name: Activate environment and run pytest (unit-only)
        shell: bash -l {0}
        run: |
          conda activate justnews-pinned
          # Ensure pytest is available
          pip install -U pip setuptools wheel
          pip install pytest
          pytest -q -k "not integration" --maxfail=1
