name: DEPRECATED CI (Docker-based)

on:
  workflow_dispatch:

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Docker deprecated notice
        run: |
          echo "This workflow is deprecated. Docker and Compose are removed from the codebase."
          echo "Use systemd scripts in deploy/systemd/ for local runs."
