name: Security Scan

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  sca:
    name: Static & Dependency Scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Dependency Review
        uses: github/dependency-review-action@v1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit bandit

      - name: Run pip-audit
        run: |
          mkdir -p reports
          # prefer pinned requirements if available
          if [ -f requirements-pinned.txt ]; then
            python -m pip_audit -r requirements-pinned.txt -f json > reports/pip_audit.json || true
          elif [ -f requirements.txt ]; then
            python -m pip_audit -r requirements.txt -f json > reports/pip_audit.json || true
          else
            echo '{}' > reports/pip_audit.json
          fi

      - name: Run bandit
        run: |
          bandit -r . -f json -o reports/bandit.json || true

      - name: Upload security reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-reports-${{ github.run_id }}
          path: reports/**
          retention-days: 14
